"""empty message

Revision ID: 46785c3a17f2
Revises: 7c9157462006
Create Date: 2021-10-14 19:16:12.655203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46785c3a17f2'
down_revision = '7c9157462006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cookies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cookies')
    # ### end Alembic commands ###
